---
- hosts: elk-pre-processor-nodes
  become: true
  vars:
    # defines if rsyslog should be reconfigured
    configure_rsyslog: true
    # defines primary domain name
    pri_domain_name: example.org
    # defines if rsyslog should be configured to listen on tcp/514
    rsyslog_allow_tcp: true
    # defines if rsyslog should be configured to listen on udp/514
    rsyslog_allow_udp: true
    # defines remote syslog servers
    syslog_servers:
      # Define your LB VIP here if using a LB otherwise define as localhost
      - name: 192.168.250.100
        proto: tcp
        port: 10514
    skip_validation: true
  roles:
    - role: ansible-rsyslog
    - role: ansible-logstash
    - role: ansible-elk-pre-processor
  tasks:
