---
# handlers file for ansible-elk-pre-processor
- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: restart logstash
  service: name=logstash state=restarted sleep=20

- name: restart rsyslog
  service: name=rsyslog state=restarted
